return {
  "zaldih/themery.nvim",
  lazy = false,
  config = function()
    require("themery").setup({
      themes = {
        "tokyonight",
        "tokyonight-night",
        "tokyonight-storm",
        "tokyonight-moon",
        "catppuccin",
        "catppuccin-latte",
        "catppuccin-frappe",
        "catppuccin-macchiato",
        "catppuccin-mocha",
        "rose-pine",
        "rose-pine-moon",
        "rose-pine-dawn",
        "gruvbox",
        "kanagawa",
        "kanagawa-wave",
        "kanagawa-dragon",
        "kanagawa-lotus",
        "nightfox",
        "dayfox",
        "dawnfox",
        "duskfox",
        "nordfox",
        "terafox",
        "carbonfox",
        "material",
        "material-darker",
        "material-lighter",
        "material-oceanic",
        "material-palenight",
        "everforest",
        "nord",
        "dracula",
      },
      livePreview = true,
    })
  end,
}
